// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFsLGAUzY256h4ZHKSfSrjMXBLz6BEd84',
    appId: '1:1002308962541:web:decc2766cb283e16e9e4e4',
    messagingSenderId: '1002308962541',
    projectId: 'smq-ee',
    authDomain: 'smq-ee.firebaseapp.com',
    storageBucket: 'smq-ee.firebasestorage.app',
    measurementId: 'G-K371N5XM9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPEX7z7nqIZTDrFEJre015sqR6RXPnQk',
    appId: '1:1002308962541:android:3b76991b5dce45a7e9e4e4',
    messagingSenderId: '1002308962541',
    projectId: 'smq-ee',
    storageBucket: 'smq-ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzqMA_YZQ307f1lWLPNAcPD2DLCfPXFxc',
    appId: '1:1002308962541:ios:82a589bc3a4ceb03e9e4e4',
    messagingSenderId: '1002308962541',
    projectId: 'smq-ee',
    storageBucket: 'smq-ee.firebasestorage.app',
    iosBundleId: 'com.example.smq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzqMA_YZQ307f1lWLPNAcPD2DLCfPXFxc',
    appId: '1:1002308962541:ios:82a589bc3a4ceb03e9e4e4',
    messagingSenderId: '1002308962541',
    projectId: 'smq-ee',
    storageBucket: 'smq-ee.firebasestorage.app',
    iosBundleId: 'com.example.smq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFsLGAUzY256h4ZHKSfSrjMXBLz6BEd84',
    appId: '1:1002308962541:web:db248ef5e34ce7ffe9e4e4',
    messagingSenderId: '1002308962541',
    projectId: 'smq-ee',
    authDomain: 'smq-ee.firebaseapp.com',
    storageBucket: 'smq-ee.firebasestorage.app',
    measurementId: 'G-C1PVVBSBSL',
  );
}
